apiVersion: v1
kind: Service
metadata:
  name: backend-service-loadbalancer
spec:
  selector:
    app: hello-world   # Match pods with label "app: my-app"
  ports:
    - protocol: TCP
      port: 8080   # Port exposed on the service
      targetPort: 8080   # Port on the pods
  type: LoadBalancer
