# cron-job.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-kubernetes
spec:
  schedule: "* * * * *"  # every min runs
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: #Either Allow(parallel), Forbid(sequential), or Replace(cancels current creates new one)
  failedJobsHistoryLimit: 0
  # suspend: true # to suspend needs to apply this for resume set it to false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: busybox
              command: ["echo", "Hello-Kubernetes!!!"]
          restartPolicy: Never