apiVersion: v1
kind: Service
metadata:
  name: helper-service-nodeport
spec:
  selector:
    app: helper-micro001
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32004
  type: NodePort
