apiVersion: v1
kind: Service
metadata:
  name: helper-service-nodeport
spec:
  selector:
    app: helper-micro001
  ports:
    - protocol: TCP
      port: 8081          # Port exposed by the service
      targetPort: 8081     # Port exposed by the container in the deployment
      nodePort: 32000      # Port to expose on each Node (between 30000-32767)
  type: NodePort
