apiVersion: v1
kind: Service
metadata:
  name: helper-service-loadbalancer
spec:
  selector:
    app: helper-micro001
  ports:
    - protocol: TCP
      port: 8081        # The port that the service will expose
      targetPort: 8081 # The port inside the container
  type: LoadBalancer
