create table product (
    id       bigint generated by default as identity primary key,
    sku      varchar(64)  not null unique,
    name     varchar(255) not null,
    quantity integer      not null check (quantity >= 0)
);

create table reservation (
    id         bigint generated by default as identity primary key,
    order_ref  varchar(64) not null unique,
    sku        varchar(64) not null references product (sku),
    quantity   integer     not null check (quantity > 0),
    status     varchar(16) not null,
    created_at timestamp   not null
);
