create table orders (
    id              bigint generated by default as identity primary key,
    order_ref       varchar(64)  not null unique,
    idempotency_key varchar(100) unique,
    sku             varchar(64)  not null,
    quantity        integer      not null check (quantity > 0),
    status          varchar(16)  not null,
    failure_reason  varchar(255),
    created_at      timestamp    not null,
    updated_at      timestamp    not null,
    version         bigint       not null default 0
);

-- list endpoint sorts by newest first
create index idx_orders_created_at on orders (created_at desc);
