server.port=8081
testing.property=${TESTING_PROPERTY:local-default}
# File written by helperdeployEmptyDirVolume.yaml into the shared emptyDir volume
cache.file.path=${CACHE_FILE_PATH:/cache/myfile.txt}
